Implementing Sonar Scan

diff --git a/.github/workflows/2_evidence-and-policy-check.yml b/.github/workflows/2_evidence-and-policy-check.yml
--- a/.github/workflows/2_evidence-and-policy-check.yml
+++ b/.github/workflows/2_evidence-and-policy-check.yml
@@ -31,6 +31,8 @@ env:
   KEY_ALIAS: evidence-key
   # Project Name
   JF_PROJECT: ${{ vars.JF_PROJECT }}
+  # SonarQube Scan Result File Name
+  SONAR_RESULT_FILE: sonar-results.json
 
 
 jobs:
@@ -111,6 +113,34 @@ jobs:
           --build-name ${{ vars.BUILD_NAME }} \
           --build-number ${{ github.run_number }}
 
+      - name: Run SonarScanner
+        id: run-sonar-scanner
+        env:
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+        run: |
+          $PWD/sonar-scanner-6.2.1.4610/bin/sonar-scanner \
+            -Dsonar.projectKey=test-evidence \
+            -Dsonar.organization=my-evidence-test-org \
+            -Dsonar.host.url=https://sonarcloud.io \
+            -Dsonar.java.jdkHome=$JAVA_HOME \
+            -Dsonar.verbose=true \
+            -Dsonar.token=$SONAR_TOKEN
+          # create evidence from sonar-scan analysis
+          set +e
+          # --FailOnAnalysisFailure causes a failure on gateway-failed sonar analysis 
+          ./examples/sonar-scan-example/bin/sonar-scan-extractor-linux-amd64  --reportTaskFile=$PWD/.scannerwork/report-task.txt > ${{ env.SONAR_RESULT_FILE }}
+          EXIT_CODE=$?
+          set -e          
+          # write the exit code to the github output so that it can be used in the evidence creation step
+          echo "------predicate.json------"
+          cat predicate.json
+          echo "------sonar-scan.log------"
+          cat sonar-scan.log
+          echo "------EXIT------"
+          echo "create-sonar-evidence=$EXIT_CODE" 
+          echo "create-sonar-evidence=$EXIT_CODE" >> $GITHUB_OUTPUT 
+
+
       - name: Create and Attach Evidence on Docker Image
         run: |
           echo '{ "actor": "${{ github.actor }}", "date": "'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'" }' > sign.json
@@ -122,7 +152,7 @@ jobs:
           --key-alias ${{ env.KEY_ALIAS }} \
           --predicate ./sign.json \
           --predicate-type https://jfrog.com/evidence/signature/v1 
-          echo '🔎 Evidence attached: `signature` 🔏 ' 
+          echo '🔎 Evidence attached: `signature` 🔏 '
 
       - name: Upload README file
         run: |
@@ -149,7 +179,7 @@ jobs:
       - name: Publish Build Info
         run: jfrog rt build-publish ${{ vars.BUILD_NAME }} ${{ github.run_number }}
 
-      - name: Sign Build Evidence
+      - name: Create and Attach Build Actor & Timestamp Evidence
         run: |
           echo '{ "actor": "${{ github.actor }}", "date": "'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'" }' > sign.json
           jf evd create \
@@ -160,6 +190,19 @@ jobs:
           --key-alias ${{ env.KEY_ALIAS }} \
           --project ${{ env.JF_PROJECT }}
           echo '🔎 Evidence attached: `build-signature` 🔏 ' >> $GITHUB_STEP_SUMMARY
+
+      - name: Attach SonarQube Scan Result Evidence
+        if: ${{ steps.run-sonar-scanner.outputs.create-sonar-evidence == 0 }}
+        run: |
+          # Attach evidence onto build using JFrog CLI                
+          jf evd create \
+            --build-name ${{ vars.BUILD_NAME }} \
+            --build-number "${{ github.run_number }}" \
+            --predicate ${{ env.SONAR_RESULT_FILE }} \
+            --predicate-type https://jfrog.com/evidence/sonar-scan/v1 \
+            --key "${{ secrets.PRIVATE_KEY_NAME }}" \
+            --key-alias ${{ env.KEY_ALIAS }} \
+            --project ${{ env.JF_PROJECT }}
 
       - name: Create Release Bundle
         run: |
