CCS-4 - Sonar scanning evidence 24

diff --git a/.github/workflows/sonar-evidence-example.yml b/.github/workflows/sonar-evidence-example.yml
--- a/.github/workflows/sonar-evidence-example.yml
+++ b/.github/workflows/sonar-evidence-example.yml
@@ -66,8 +66,19 @@ jobs:
           echo "---------------------"
           cat .scannerwork/report-task.txt
           echo "---------------------"
-          
-          ./examples/sonar-scan-example/bin/sonar-scan-extractor-linux-amd64  $PWD/.scannerwork/report-task.txt
+          set +e                # Allow the script to continue on error
+          ./examples/sonar-scan-example/bin/sonar-scan-extractor-linux-amd64  $PWD/.scannerwork/report-task.txt > predicate.json
+          exit_code=$?         # Capture the exit code
+
+          # Check the exit code
+          if [ $exit_code -ne 0 ]; then
+            echo "Your script failed with exit code: $exit_code"
+            cat predicate.json
+          else
+            echo "Your script completed successfully."
+            cat predicate.json
+          fi
+          set -e 
           # Attach evidence onto build using JFrog CLI                
           #jf evd create \
           #  --build-name "${{ env.BUILD_NAME }}" \
@@ -76,37 +87,4 @@ jobs:
           #  --predicate-type https://jfrog.com/evidence/sonar-scan/v1 \
           #  --key "${{ secrets.JIRA_TEST_PKEY }}" \
           #  --key-alias ${{ vars.JIRA_TEST_KEY }}
-
-
-      - name: Log in to Artifactory Docker Registry
-        uses: docker/login-action@v3
-        with:
-          registry: ${{ vars.ARTIFACTORY_URL }}
-          username: ${{ steps.setup-cli.outputs.oidc-user }}
-          password: ${{ steps.setup-cli.outputs.oidc-token }}
-
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
-
-      - name: Build and Push Docker image
-        uses: docker/build-push-action@v6
-        id: docker-build
-        with:
-          push: true
-          provenance: false
-          platforms: linux/amd64 #, linux/arm64
-          build-args: REPO_URL=${{ vars.JF_URL }}/example-project-docker-dev-remote
-          tags: ${{ vars.JF_URL }}/${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME }}
-
-      - name: add docker package to build
-        run: |
-          echo "${{ vars.JF_URL }}/${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME }}@${{ steps.docker-build.outputs.digest }}" > metadata.json
-          jf rt build-docker-create ${{ env.DOCKER_REPO }} --image-file metadata.json --build-name ${{ env.BUILD_NAME }} --build-number ${{ github.run_number }}
-
-      - name: Publish build info
-        if: ${{ true }}
-        run: |
-          jf rt build-collect-env
-          jf rt build-add-git
-          jf rt build-publish
 
